### PR TITLE
Bug Fix and Feature Add

### PR DESCRIPTION
**Pull request by jaalfaro**
Fixed issue where recursive search used findFile vs findFiles
Added support to not do a recursive search

### CODE REVIEW

**Comment by ZECTBynmo** [comment]
Nice

**Comment by marcusgreenwood** [comment]
Please can you release a new version on npm for this fix :)

**Comment by ZECTBynmo** [comment]
Sure, one moment

**Comment by ZECTBynmo** [comment]
All set, just published version 0.1.2

**Comment by marcusgreenwood** [comment]
Thanks

**Pull request merged**
